### ISSUE TITLE
Troubleshooting Component Issues: iPhone and Mac Compatibility Challenges vs. Arc Browser Success

### ISSUE THREAD

**Issue by msoaresp** [tdvtdv/ha-tdv-bar#11]
The component isn't working on iPhone and Mac apps. On the iPhone, it doesn't even recognize it and reports "Custom element doesn't exist: tdv-bar-card. On the Mac, it doesn't assemble correctly and doesn't display any information.

However, in the Arc browser, it works perfectly.

**Comment by tdvtdv** [comment]
The problem has been fixed in version 1.2.3
