### ISSUE TITLE
Rendering in Iphone when is container 

### ISSUE THREAD

**Issue by Axenwood** [tdvtdv/ha-tdv-bar#15]
Hello

Thank you very much for this fantastic tool.

I have noticed if I put in a grid, or inside another card it won't display properly, it all scrunch's up into about 10% of the allocated size.

Thanks again

**Comment by Axenwood** [comment]
HeyThanks for the tipSent from my iPhoneOn 1 Aug 2024, at 9:23 pm, JAGS77 ***@***.***> wrote:﻿
Copy into a horizontal stack. It works

**Comment by tdvtdv** [comment]
The problem has been fixed in version 1.2.3
