### ISSUE TITLE
Request: Default Name and Icon

### ISSUE THREAD

**Issue by Revilo91** [tdvtdv/ha-tdv-bar#2]
It would be nice if the name and icon came from the entity itself and not just left blank. 

Currently you have to specify the name and icon yourself.

**Comment by tdvtdv** [comment]
It's easy to fix the entity name, but not the icon.
Devices don't have an icon associated with them, it can only take an icon associated with the sensor entity

I will fix these shortcomings in the next release. Thanks for the request.
