### ISSUE TITLE
Request: Track All Option

### ISSUE THREAD

**Issue by melvanderwal** [tdvtdv/ha-tdv-bar#6]
Hi there.   I really like this card, it's fantastic for looking at my different solar PV panel arrays.

A suggestion:  it would be nice to have a trackall binary option.  The behaviour would be that if it is set to 1, hovering the mouse over any graph would update the bars for all graphs in the card for that point in time.  If it is set to 0, hovering the mouse over a graph would update the bar for only that graph (i.e. the current behaviour).

The benefit would be that you can instantly compare what is happening for all sensors at a given point in time, rather than needing to hover over each one individually and find the same point in time for each.

Thanks for the nice card and for your consideration!

**Comment by tdvtdv** [comment]
Added a new mouse tracking mode that draws a bar chart for all entities

**Comment by melvanderwal** [comment]
@tdvtdv - thank you so much, this is perfect.   Adding it as an option to trackingmode is very nice, elegant implementation.
