### ISSUE TITLE
Display negative values possible?

### ISSUE THREAD

**Issue by acdcnow** [tdvtdv/ha-tdv-bar#7]
HI,
I do have a power sensor then moved into negative value but they are not shown it looks like that at 0 all values are cut of.
Any change to get a flag to display as well negative?

**Comment by MikeatLorne** [comment]
I love the card but it would be even better if negative values can be displayed - I have a battery for my house and it currently shows a "masked" value when charging

**Comment by Newevg** [comment]
+1 - Please implement Negative!

**Comment by raspitoaster** [comment]
+1 for the negative values. I love this card and I configured it to see the current and latest energy of all my relevant devices on one page. Very handy on mobile devices.

**Comment by garybrown9119** [comment]
+1 for negative values.  My battery shows negative when discharing and positive when charging.  Would be great to show this.  Or if possible, be able to show bar in different color based on +ve or -ve values.   Loving how simple & clear this diaplays the entities.

**Comment by Econut** [comment]
yes i would love this feature too so that it would show battery discharge that require to be able to show a negative figure

thanks

**Comment by tdvtdv** [comment]
Added negative scale support in version 1.2.0
